CREATE TABLE `USER_ACCOUNT` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID` VARCHAR(32) NOT NULL UNIQUE,
  `EMAIL_ADDRESS` VARCHAR(128) NOT NULL UNIQUE,
--  `IDENTITY` VARCHAR(80) NOT NULL UNIQUE,
  `PASSWORD` VARCHAR(128) NOT NULL,
  `AUTHORITY` INT(11) NOT NULL DEFAULT '0',
  `ACCOUNT_LOCK` BOOLEAN,
  `ACCOUNT_EXPIRATION_DATE` DATE,
  `PASSWORD_EXPIRATION_DATE` DATE,
  `ACCOUNT_GROUP` TEXT,
  `TELEPHONE1` VARCHAR(15),
  `TELEPHONE2` VARCHAR(15),
  `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  INDEX (`ACCOUNT_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8
